name: Test schedule

on:
  schedule:
    - cron: '3,18,33,48 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar hora UTC
        run: |
          echo "UTC:"
          date -u
          echo "Runner local:"
          date
